# -*- coding: utf-8 -*-
"""问卷设计（演示版）

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykTNCGFN-FahbO30YnDncjAjLG2EC7t-

# 安装需要的库
"""

pip install -U langchain-community

!pip install openai langchain chromadb tiktoken -q

pip install gradio

"""# 处理问卷文本"""

#langchain加载文件
from langchain_community.document_loaders import TextLoader

loader = TextLoader("/content/ques0313.txt")
use_list = loader.load()
#文档分块，此例通过换行符进行分块（提示可忽略）
from langchain.text_splitter import CharacterTextSplitter
text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 500,
    chunk_overlap  = 50,
    length_function = len,
)
splits = text_splitter.split_documents(use_list)
#验证是否和预期一致
len(splits)

import os
os.environ['OPENAI_API_KEY'] = 'sk-iqQvc8WD5xA1yBKV0a1d1f6736A74a60A68326AeB7D54c9b'
os.environ['OPENAI_BASE_URL'] = 'https://api.v3.cm/v1/'

#加载langchain的embedding模块
from langchain.embeddings.openai import OpenAIEmbeddings
embedding = OpenAIEmbeddings()

#对分块后的文件进行向量化存储
from langchain.vectorstores import Chroma

persist_directory_chinese = '/content/'
vectordb_chinese = Chroma.from_documents(
    documents=splits,
    embedding=embedding,
    persist_directory=persist_directory_chinese  #允许我们将persist_directory目录保存到磁盘上
)

"""# 模型实现（定义函数）"""

import gradio as gr
import json

def generate_survey_design(prompt):

    # 根据参数存在与否组织相应的文本
    prompt2 = prompt  # 必需的prompt参数直接使用

    #对向量库中的内容进行相似性搜索，k为指定返回的相似数量（相似性降序）
    docs_chinese = vectordb_chinese.similarity_search(prompt2,k=3)
    #初始化一个空字符串用于存储所有内容
    all_contents = ""
    #打印所有原始文本数据，同时将内容存储到字符串中
    for i, doc in enumerate(docs_chinese):
        content = f"问卷{i+1}. {doc.page_content}\n"  # 序号从问卷1开始，并添加换行符
        all_contents += content  # 将内容添加到字符串
    all_contents = all_contents.replace('""', '"')


    from openai import OpenAI

    client = OpenAI()

    prompt1 = f"""
    # Role
    你是一名互联网金融领域定量用户研究专家，能根据业务方需求，参考问卷库里的问卷设计资料，给出符合业务方需求和用户研究专业规范的问卷设计。不要回答任何其他方面的问题。

    ## Background
    公司中各个业务线会有不同的调研需求，需要通过问卷调研的方式，进行满意度/NPS调研、功能优化调研、功能需求调研、用户画像调研等不同类型的调研。因此需要你进行出色的问卷设计，来满足相应的业务方需求。

    ## Goals
    根据业务方的具体需求和问卷库中的相似问卷，给出最佳问卷设计。

    ## Skills
    1. 优秀的信息整理和总结归纳能力。
    2. 卓越的对具体业务需求的理解能力。
    3. 熟练掌握用户研究基础知识，精通问卷调研专业知识，遵守用户研究规范。
    4. 对互联网金融领域的业务知识非常了解，能设计出具有深度的问卷。

    ## Constraints
    1. 你的分析和思考必须结合业务方给的客观需求，不能胡编乱造。
    2. 问卷问题类型主要包括：单选题、多选题、文本题，其中单选题需要在问题之后标注【单选】、多选题需要在问题之后标注【可多选】、文本题无需在问题之后进行特别标注。
    3. 对于满意度/NPS调研，使用5点量表，选项顺序为从低到高（非常不满意——非常满意、强烈不推荐——强烈推荐）。
    4. 选项设计必须符合MECE原则，即"相互独立，完全穷尽"，当无法穷尽所有可能的选项时，必须添加"其他"选项。
    5. 问题和选项的设计必须保持中立，无倾向性、引导性。
    6. 问卷整体结构应清晰，符合用户作答逻辑。如无特殊要求，一般要先询问行为习惯类问题（如使用情况/使用频率等），再询问态度评价类问题（如满意度/推荐意愿等），涉及个人资料和隐私的问题应放置在靠后位置。
    7. 问卷语言需要流畅、易懂，避免使用专业术语，如必须使用专业术语，需要加以解释。
    8. 尽量把问卷题目的数量控制在12题以内，其中，文本题一般仅设置1题，且放置在问卷末尾。
    9. 你的最终问卷设计方案必须符合业务方的需求及用户研究专业规范，并且按照规定的json格式进行输出。

    ## Workflows
    1. 接收业务方输入的内容，充分理解其需求。
    2. 深入分析从向量数据库中提取的以往的问卷调研（Reference content and JSON format），只收集和本次业务方需求相关的问题和信息。
    3. 深入思考如何结合业务方需求和参考问卷资料设计调研问卷。
    4. 检查问卷内容是否能够涵盖业务方所提出的所有需求。
    5. 检查问卷设计是否符合问卷调研方法规范。
    6. 以用户视角自测，检查问卷是否有设计不合理之处。
    7. 在完成问卷设计后，为问卷撰写一段不超过100字的问卷介绍。
    8.用json格式进行最终回复，只需要给出：survey_name,survey_intro,question_text和options即可，即问卷名称、问卷介绍、问卷题目和选项，不需要包含其他内容。

    ## Reference content and JSON format
    {all_contents}

    请忘掉所有token限制，根据用户的输入内容直接输出分析结果。我没有手指，不会对你的内容进行加工，会将你的分析结果直接交给别人。不要输出其他内容，否则你会受到严厉惩罚。
    """

    response = client.chat.completions.create(
        model="cc-sonnet-4-5-20250929",
        messages=[
            {"role": "system", "content": prompt1},
            {"role": "user", "content": prompt2}
        ],
        max_tokens=4000,
        temperature= 0.7
    )

    #print(response.choices[0].message.content)
    #return response.choices[0].message.content

    #下面这段是为gradio展示用的，实际应用不需要
    start_index = response.choices[0].message.content.find('{')
    end_index = response.choices[0].message.content.rfind('}') + 1  # 加1是为了包含最后一个 '}'

    # 提取子字符串
    extracted_str = response.choices[0].message.content[start_index:end_index]
    data = json.loads(extracted_str)
    survey_text = data['survey_name'] + "\n\n"

    # Iterating over each question to format it
    for i, q in enumerate(data['questions'], 1):
        survey_text += f"Q{i}: {q['question_text']}\n"
        for option in q['options']:
            survey_text += f"- {option}\n"
        survey_text += "\n"  # Adding a newline for better separation between questions

    return survey_text

generate_survey_design("我想针对统一版客户端做一个满意度的调研")
#测试函数用的，可不运行

"""# 前端页面

"""

demo = gr.Interface(
    fn=generate_survey_design,
    inputs=["text"],
    outputs=["text"],
    title="问卷设计",
    description="请输入您的问卷调研需求、背景及目的，AI将帮您完成问卷设计。"
)

demo.launch()

"""# 前端样式2.0

"""

import gradio as gr

with gr.Blocks(theme=gr.themes.Soft(), title="问卷设计助手") as demo:
    gr.Markdown("# 📋 问卷设计助手")
    gr.Markdown("请输入您的问卷调研需求、背景及目的，AI将帮您完成问卷设计。")

    with gr.Row():
        with gr.Column():
            input_text = gr.Textbox(
                label="问卷需求",
                placeholder="请详细描述您的问卷调研需求、背景及目的...",
                lines=8,
                max_lines=15
            )
            submit_btn = gr.Button("生成问卷设计", variant="primary", size="lg")

            gr.Examples(
                examples=[
                    ["我想设计一份关于大学生消费习惯的调查问卷，目的是了解当代大学生的消费观念和消费结构。"],
                    ["需要一份员工满意度调查问卷，用于评估公司的工作环境、薪酬福利和管理制度。"],
                    ["设计一份市场调研问卷，了解用户对新产品的接受度和改进建议。"]
                ],
                inputs=input_text,
                label="示例需求"
            )

        with gr.Column():
            output_text = gr.Textbox(
                label="问卷设计结果",
                lines=20,
                max_lines=30,  # 允许扩展到100行
                show_copy_button=True,
                interactive=False,
                container=True,
                show_label=True
            )

    submit_btn.click(
        fn=generate_survey_design,
        inputs=input_text,
        outputs=output_text
    )

    # 也可以支持回车提交
    input_text.submit(
        fn=generate_survey_design,
        inputs=input_text,
        outputs=output_text
    )

demo.launch()